Lab/fisrt prog
Pritex007/IU5-iOS-2022 pull request #1
Opened 2022-02-27 17:15 UTC by Pritex007

## Товарищ, твой PR - твоя гордость!

- [ ] Убедись, что все тесты прошли успешно.
- [ ] Проверь, что Pull Request таргетоирован в ТВОЙ ФОРКНУТЫЙ main
- [ ] Заполни отчет по лабораторной работе в Google форме
- [ ] Улыбнись, ведь ты приобрел новые навыки)

## Важно!

После того, как ты заполнишь отчет по лабе, я или Юра поревьюим его, и напишем комментарии к коду, если будут вопросы.

Когда ты увидишь коментарий "Все ОК, мержи", можешь смержить PR.

- [ ] Ты увидел "Все ОК, мержи"?

2022-02-28 21:26 UTC, MrOcumare requested changes

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_0/SwapValues.swift
> +        employeePayroll.luppaSalary = employeePayroll.luppaSalary - employeePayroll.puppaSalary
отлично

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +        if (array.count == 0){
переделай через guard

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +        var startVal : Int = array[0]
тут и выше типы не нужны 
и если пишешь типы то делай var result: String = ""

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +            if(abs(array[i-1] - array[i]) <= 1){
скобки тут не нужны

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +                if(startVal == array[i-1]){
тоже скобки не нужны

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +            if(abs(array[i-1] - array[i]) <= 1){
добавь отступы array[i - 1]

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +                if(startVal == array[i-1]){
+ отступы

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +        if(startVal == array[array.count-1]){  //проверка последнего элемента массива
комментарии в коде пишутся над строчками

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/ArrayToString.swift
> +        if(startVal == array[array.count-1]){  //проверка последнего элемента массива
тоже поправь codestyle

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/BooleanConverter.swift
> +        case "YES": return BoolValues.yes
не )
на новой строчке пиши 
switch string {
case "YES": 
    return BoolValues.yes
    
примерно такой codeStyle у switch case

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/BooleanConverter.swift
> +        default: return BoolValues.veryBad(value : string)
зачем тут default ?
убирай, и напеши через case veryBad

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/NumberToArray.swift
> +        var count : Int = 1
так же все плохо с codeStyle

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/NumberToArray.swift
> +        return Array
решение не принимается 
подумай как сделать через один цикл

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/SequenceСreator.swift
> +        return sequence
опять таки поработай над codestyle

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/SequenceСreator.swift
> +        if (finalElement > 0){
скобки () не нужны
перед { не забывай ставить пробел

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/SequenceСreator.swift
> +        if (finalElement > 0){
лучше перепиши через guard

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/SequenceСreator.swift
> +            sequence.append(i+1)
i + 1

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/SequenceСreator.swift
> +        if (finalElement > 0){
и сделай проверку в самом начале, перед созданием переменной 
ибо, если придут невалидные данные, тебе нет нужды создать переменные, сразу кидаешь return

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/SequenceСreator.swift
> +        return sequence
тут все тоже самое что и выше

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/SquareSum.swift
> +        var sum : Int = 0
codestyle

2022-02-28 21:26 UTC, MrOcumare commented on LABS/LAB_1/SquareSum.swift
> +            sum = sum + i * i
а почему бы не сделать через операцию степени?)

2022-02-28 21:27 UTC, MrOcumare commented
В целом, норм)
поправляй)

2022-03-01 10:41 UTC, Pritex007 commented on LABS/LAB_1/BooleanConverter.swift
> +        default: return BoolValues.veryBad(value : string)
По заданию всё, что отлично от "YES" или "NO", возвращает veryBad. Не понимаю в чём проблема.

2022-03-01 17:40 UTC, Pritex007 commented on LABS/LAB_1/SquareSum.swift
> +            sum = sum + i * i
Done

2022-03-01 17:41 UTC, Pritex007 commented on LABS/LAB_1/SequenceСreator.swift
> +        if (finalElement > 0){
Done

2022-03-01 17:41 UTC, Pritex007 commented on LABS/LAB_1/SequenceСreator.swift
> +            sequence.append(i+1)
Done

2022-03-01 17:41 UTC, Pritex007 commented on LABS/LAB_1/SquareSum.swift
> +        var sum : Int = 0
Done

2022-03-01 17:41 UTC, Pritex007 commented on LABS/LAB_1/SequenceСreator.swift
> +        return sequence
Done

2022-03-01 17:41 UTC, Pritex007 commented on LABS/LAB_1/ArrayToString.swift
> +                if(startVal == array[i-1]){
Done

2022-03-01 17:41 UTC, Pritex007 commented on LABS/LAB_1/ArrayToString.swift
> +            if(abs(array[i-1] - array[i]) <= 1){
Done

2022-03-01 17:41 UTC, Pritex007 commented on LABS/LAB_1/ArrayToString.swift
> +        var startVal : Int = array[0]
Done

2022-03-01 17:41 UTC, Pritex007 commented on LABS/LAB_1/ArrayToString.swift
> +        if (array.count == 0){
Done

2022-03-01 17:41 UTC, Pritex007 commented on LABS/LAB_0/SwapValues.swift
> +        employeePayroll.luppaSalary = employeePayroll.luppaSalary - employeePayroll.puppaSalary
Done

2022-03-01 17:41 UTC, Pritex007 commented on LABS/LAB_1/ArrayToString.swift
> +        if(startVal == array[array.count-1]){  //проверка последнего элемента массива
Done

2022-03-01 17:41 UTC, Pritex007 commented on LABS/LAB_1/BooleanConverter.swift
> +        case "YES": return BoolValues.yes
Done

2022-03-01 17:41 UTC, Pritex007 commented on LABS/LAB_1/NumberToArray.swift
> +        var count : Int = 1
Done

2022-03-01 17:41 UTC, Pritex007 commented on LABS/LAB_1/NumberToArray.swift
> +        return Array
Done

2022-03-01 20:00 UTC, MrOcumare commented on LABS/LAB_1/BooleanConverter.swift
> +        default: return BoolValues.veryBad(value : string)
Смотри, испольщовать default нужно в очень редких случаях
здесь лучше сделать через 
case veryBad(value: String)

ибо если добавишь потом 
case "BIBA": return BoolValues.BIBA
у тебя это так же будет сыпаться в default

2022-03-02 09:23 UTC, Pritex007 commented on LABS/LAB_1/BooleanConverter.swift
> +        default: return BoolValues.veryBad(value : string)
Если я в Enum BoolValues добавлю "case BIBA" и перед default "case "BIBA": return BoolValues.BIBA" всё будет работать нормально. При добавлении новых значений для отслеживания в любом случае придётся вносить изменения в оба блока(Enum, switch). Я бы с вами согласился, если бы я использовал switch от BoolValues, но здесь я должен охватить все случаи, кроме "YES" и "NO". У меня default в switch, а не в Enum. Поэтому не понимаю, как вы хотите, чтоб я исправил.

2022-03-02 16:34 UTC, Pritex007 commented on LABS/LAB_1/BooleanConverter.swift
> +        default: return BoolValues.veryBad(value : string)
> Смотри, испольщовать default нужно в очень редких случаях здесь лучше сделать через case veryBad(value: String)
> 
> ибо если добавишь потом case "BIBA": return BoolValues.BIBA у тебя это так же будет сыпаться в default

2022-03-03 19:50 UTC, MrOcumare commented
Все Ок, мержи

2022-03-04 12:34 UTC, merged